server:
  port: 8084
spring:
  application:
    name: EUREKA-CLIENT
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8759/eureka
