server:
  port: 9999
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zp961004/MyRoom.git
          search-paths: Test-Config
          username: zp961004
          password: A590256b891213

      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8759/eureka/